CREATE DATABASE CLINICA
GO 
USE CLINICA
GO

CREATE TABLE PACIENTE(
IDPACIENTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL,
DOCUMENTO INT NOT NULL UNIQUE,
FNAC DATE NOT NULL,
IDOBSOCIAL INT NOT NULL FOREIGN KEY REFERENCES OBRASOCIAL(IDOS),
NROAFILIADO INT NOT NULL UNIQUE,
IDDIRECCION INT NOT NULL FOREIGN KEY REFERENCES DIRECCIONES(IDDIRECCION)
)

GO
drop table paciente

CREATE TABLE MEDICOS(
IDMEDICO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
EDAD INT NOT NULL,
FNAC DATE NOT NULL,
NMATRICULA INT NOT NULL,
IDESPECIALIDAD INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES(IDESPECIALIDAD)
)
GO

CREATE TABLE LOCALIDADES(
IDLOCALIDAD INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CPOSTAL VARCHAR(20) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL
)
GO

CREATE TABLE DIRECCIONES(
IDDIRECCION INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CALLE VARCHAR(50) NOT NULL,
NUMERO INT NOT NULL,
IDLOCALIDAD INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(IDLOCALIDAD)
)
GO



CREATE TABLE ESPECIALIDADES(
IDESPECIALIDAD INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR (50) NOT NULL
)
GO

CREATE TABLE OBRASOCIAL(
IDOS INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(20) NOT NULL,
TELEFONO INT NOT NULL,
MAIL VARCHAR(50) NOT NULL
)
GO
----------------------CONSULTAS------------------------------------
DROP TABLE OBRASOCIAL
DROP TABLE LOCALIDADES
DROP TABLE DIRECCIONES
DROP TABLE PACIENTE

SELECT * FROM LOCALIDADES
SELECT * FROM DIRECCIONES
SELECT * FROM PACIENTE
SELECT * FROM ESPECIALIDADES

INSERT INTO LOCALIDADES VALUES('123', 'TIGRE')
INSERT INTO LOCALIDADES VALUES('456', 'SAN FERNANDO')
INSERT INTO LOCALIDADES VALUES('789', 'PACHECO')
INSERT INTO LOCALIDADES VALUES('101', 'SAN ISIDRO')
INSERT INTO LOCALIDADES VALUES('102', 'MARTINEZ')

