CREATE DATABASE CLINICA
GO 
USE CLINICA
GO

CREATE TABLE PACIENTE(
IDPACIENTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL,
EDAD INT NOT NULL,
DOCUMENTO INT NOT NULL UNIQUE,
FNAC DATE NOT NULL,
OBSOCIAL VARCHAR(20) NOT NULL,
IDOBSOCIAL INT NOT NULL
)
GO

CREATE TABLE ESPECIALIDADES(
IDESPECIALIDAD INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR (50) NOT NULL
)
GO

SELECT * FROM ESPECIALIDADES